--　コメントテーブルの作成
CREATE TABLE COMMENT_TBL
(
    COMMENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'コメントID' ,
    NAME NVARCHAR(20) COMMENT '名前',
    COMMENT NVARCHAR(100) COMMENT 'コメント',
    INS_DATE_TIME DATETIME COMMENT '登録日時',
    UPD_DATE_TIME DATETIME COMMENT '更新日時'
)
DEFAULT charset=utf8
COMMENT 'コメントテーブル';

-- コメントテーブルの削除
DROP TABLE COMMENT_TBL;

-- コメントテーブルの定義確認
desc COMMENT_TBL;

--テストデータ
INSERT INTO comment_tbl (NAME,COMMENT,INS_DATE_TIME,UPD_DATE_TIME)
VALUES ('まつけん','テスト用のコメント',NOW(),NOW());

--レコード確認
SELECT COMMENT_ID, NAME,COMMENT,INS_DATE_TIME FROM COMMENT_TBL;


