--■ユーザテーブル
--DROP TABLE MK_USER_TBL;
CREATE TABLE MK_USER_TBL
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'ユーザID',
    USER_NAME NVARCHAR(100) COMMENT 'ユーザ名',
    PASSWORD NVARCHAR(100) COMMENT 'パスワード',
    AUTH_KBN NVARCHAR(100) COMMENT '権限区分 10:管理者, 20:一般ユーザ',
    CREATED_DATE DATETIME COMMENT '登録日',
    UPDATE_DATE DATETIME COMMENT '更新日'
)
DEFAULT charset=utf8
COMMENT 'ユーザテーブル';

INSERT INTO MK_USER_TBL (USER_NAME, PASSWORD, AUTH_KBN, CREATED_DATE, UPDATE_DATE)
VALUES
 ('admin', 'admin', '10', now(), now())
,('matuken', 'matuken', '20', now(), now());

--■商品テーブル
CREATE TABLE MK_ITEM_TBL
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '商品ID',
    NAME NVARCHAR(100) COMMENT '商品名',
    PRICE INT COMMENT '価格',
    IMG NVARCHAR(100) COMMENT '画像ファイル名',
    STATUS NVARCHAR(100) COMMENT '公開フラグ(1:公開 0:非公開)',
    CREATED_DATE DATETIME COMMENT '登録日',
    UPDATE_DATE DATETIME COMMENT '更新日'
)
DEFAULT charset=utf8
COMMENT '商品テーブル';

-- 在庫テーブル
CREATE TABLE MK_ITEM_STOCK_TBL (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '在庫ID',
    ITEM_ID INT COMMENT '商品ID',
    STOCK INT COMMENT '在庫数',
    CREATED_DATE DATETIME COMMENT '登録日',
    UPDATE_DATE DATETIME COMMENT '更新日'
)
DEFAULT charset=utf8
COMMENT '在庫テーブル';

-- CARTテーブル
CREATE TABLE MK_CART_TBL (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'カートID',
    USER_ID INT COMMENT 'ユーザID',
    ITEM_ID INT COMMENT '商品ID',
    AMOUNT INT COMMENT '購入予定数',
    CREATED_DATE DATETIME COMMENT '登録日',
    UPDATE_DATE DATETIME COMMENT '更新日'
)
DEFAULT charset=utf8
COMMENT 'カートテーブル';

--商品購入テーブル
CREATE TABLE MK_BUY_ITEM_TBL (
    BUY_CODE INT NOT NULL COMMENT '商品購入コード',
    SEQ INT NOT NULL COMMENT 'シーケンス',
    USER_ID INT COMMENT 'ユーザID',
    ITEM_ID INT COMMENT '商品ID',
    BUY_PRICE INT COMMENT '購入時価格',
    AMOUNT INT COMMENT '購入数',
    CREATED_DATE DATETIME COMMENT '登録日',
    UPDATE_DATE DATETIME COMMENT '更新日',
    PRIMARY KEY(BUY_CODE,SEQ)
)
DEFAULT charset=utf8
COMMENT '購入テーブル';
