--■ユーザテーブル
CREATE TABLE MK_USER_TBL
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'ユーザID',
    USER_NAME NVARCHAR(100) COMMENT 'ユーザ名',
    PASSWORD NVARCHAR(100) COMMENT 'パスワード',
    CREATED_DATE DATETIME COMMENT '登録日',
    UPDATE_DATE DATETIME COMMENT '更新日'
)
DEFAULT charset=utf8
COMMENT 'ユーザテーブル';

INSERT INTO MK_USER_TBL (USER_NAME, PASSWORD, CREATED_DATE, UPDATE_DATE)
values ('admin', 'admin',now(), now());

--■商品テーブル
CREATE TABLE MK_ITEM_TBL
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '商品ID',
    NAME NVARCHAR(100) COMMENT '商品名',
    PRICE INT COMMENT '価格',
    IMG NVARCHAR(100) COMMENT '画像ファイル名',
    STATUS NVARCHAR(100) COMMENT '公開フラグ(1:公開 0:非公開)',
    CREATED_DATE DATETIME COMMENT '登録日',
    UPDATE_DATE DATETIME COMMENT '更新日'
)
DEFAULT charset=utf8
COMMENT '商品テーブル';


-- 在庫テーブル
CREATE TABLE MK_ITEM_STOCK_TBL (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '在庫ID',
    ITEM_ID INT COMMENT '商品ID',
    STOCK INT COMMENT '在庫数',
    CREATED_DATE DATETIME COMMENT '登録日',
    UPDATE_DATE DATETIME COMMENT '更新日'
)
DEFAULT charset=utf8
COMMENT '在庫テーブル';
