--■ユーザテーブル
CREATE TABLE MK_USER_TBL
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'ユーザID',
    USER_NAME NVARCHAR(100) COMMENT 'ユーザ名',
    PASSWORD NVARCHAR(100) COMMENT 'パスワード',
    CREATED_DATE DATETIME COMMENT '登録日',
    UPDATE_DATE DATETIME COMMENT '更新日'
)
DEFAULT charset=utf8
COMMENT 'ユーザテーブル';

INSERT INTO MK_USER_TBL (USER_NAME, PASSWORD, CREATED_DATE, UPDATE_DATE)
values ('admin', 'admin',now(), now());