--データベースの作成
CREATE DATABASE codecampdb;

--ログイン画面で作成したDDLなど

--■ユーザテーブル
CREATE TABLE USER_TBL
(
    USER_ID NVARCHAR(20)  NOT NULL PRIMARY KEY COMMENT 'ユーザID',
    PASSWORD NVARCHAR(20) COMMENT 'パスワード',
    FAMILY_NAME NVARCHAR(15) COMMENT '名前_姓',
    FIRST_NAME NVARCHAR(15) COMMENT '名前_名',
    INS_DATE_TIME DATETIME COMMENT '登録日時',
    UPD_DATE_TIME DATETIME COMMENT '更新日時'
)
DEFAULT charset=utf8
COMMENT 'ユーザテーブル';

DESC USER_TBL;

INSERT INTO USER_TBL
(USER_ID, PASSWORD, FAMILY_NAME, FIRST_NAME, INS_DATE_TIME, UPD_DATE_TIME)
VALUES
('test', 'test', '松鷹', '憲', now(), now());

SELECT
    USER_ID,
    PASSWORD,
    FAMILY_NAME,
    FIRST_NAME,
    INS_DATE_TIME,
    UPD_DATE_TIME
FROM USER_TBL;